version: '3'

services:
  bank-http-server:
    command: "php public/index.php"
    build:
      context: ./
    working_dir: /server
    volumes:
      - ./..:/server
    environment:
      HTTP_PORT: ${HTTP_PORT}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
